repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
        args:
          - --unsafe
      - id: end-of-file-fixer
        exclude: \.Rd$
      - id: file-contents-sorter
        files: ^\.Rbuildignore$
      - id: trailing-whitespace
  - repo: https://github.com/lorenzwalthert/precommit
    rev: v0.3.2.9021
    hooks:
      - id: roxygenize
        additional_dependencies:
          - tibble
      - id: deps-in-desc
        exclude: data-raw
      - id: no-browser-statement
      - id: parsable-R
      - id: style-files
      - id: readme-rmd-rendered
      - id: use-tidy-description
