on:
  push:
    branches: [main, master]
  schedule:
    - cron: "0 0 1 * *"

name: refresh.yaml

jobs:
  refresh:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - name: Set up R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rvest any::usethis any::tidyr
      - name: Fetch latest isocountry data
        run: Rscript data-raw/isocountry.R
      - name: Fetch latest isocurrency data
        run: Rscript data-raw/isocurrency.R
      - name: commit
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add .
          git commit -m 'chore: refresh data' || exit 0
          git push origin
