on:
  schedule:
    - cron: "3 * * * *"

name: refresh

jobs:
  refresh:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - name: Set up R dependencies
        run: pak::pkg_install(c("rvest", "dplyr", "usethis"))
        shell: Rscript {0}
      - name: Refresh isocountry
        uses: Rscript data-raw/isocountry.R
      - name: Refresh isocurreny
        uses: Rscript data-raw/isocurreny.R
